### ISSUE TITLE
Create Config File Loader

### ISSUE THREAD

**Issue by terminatedNULL** [terminatedNULL/Image_Crunch#4]
Add a config file selector and loader as well as support for loading the last used config (maybe).

**Comment by AidanMayo** [comment]
config loader should just be pulled off start, items should save during runtime if altered.

**Comment by terminatedNULL** [comment]
Update config loader to return a list of all available config files. Allow for the selection of a specific config or the last loaded config.
This should probably be split up into two functions for specifically: loading the last selected configuration, and loading all available configurations.
